### ISSUE TITLE
Problème lecture sur Raspberry pi 3b+

### ISSUE THREAD

**Issue by Guibol22** [f-lawe/plugin.video.orange.fr#24]
Bonjour,

Etant arrivé chez Sosh, j'ai voulu tester le plugin sur mon Raspberry pi 3 b+. Je suis sur une fresh install de Raspberrypi os Bullseye et j'utilise la dernière version kodi qui est sur l'OS : la 19.3. 
L'installation du plugin semble s'être bien déroulée mais impossible de lire les différents flux des chaînes. A chaque fois le CPU du RPI grimpe au delà de 100% et le flux diffusé est en conséquence au ralenti et saccadé. Je ne sais pas si j'ai des modifications à faire quelque part. 
Je précise que CatchUp TV tourne parfaitement et je n'ai aucun soucis pour lire des films en 720p ou 1080p.
Merci d'avance pour votre aide

**Comment by BreizhReloaded** [comment]
Salut !
Tu as ce problème là uniquement pendant la lecture des flux TV ? Est-ce que tu as essayé la TV via CatchUp TV & More en plus du replay ? Histoire de voir si ton problème vient de la lecture des flux vidéo via PVR IPTV Simple en général, ou uniquement de Orange TV.

**Comment by FuraX49** [comment]
Bonjour
2022-03-19 12:54:20.617 T:297897    INFO <general>: Orange TV France: Loading channel 733
2022-03-19 12:54:20.837 T:297897   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following
 error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'stream_info' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.orange.fr/resources/addon.py", line 58, in <modu
le>
                                                       plugin.run()
                                                     File "/home/pi/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/pi/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/pi/.kodi/addons/plugin.video.orange.fr/resources/addon.py", line 24, in chann
el
                                                       stream = get_provider().get_stream_info(channel_id)
                                                     File "/home/pi/.kodi/addons/plugin.video.orange.fr/resources/lib/providers/provider_wrapp
er.py", line 24, in get_stream_info
                                                       return self.provider.get_stream_info(channel_id)
                                                     File "/home/pi/.kodi/addons/plugin.video.orange.fr/resources/lib/provider_templates/orang
e.py", line 45, in get_stream_info
                                                       for system in stream_info.get('protectionData'):
                                                   UnboundLocalError: local variable 'stream_info' referenced before assignment
                                                   -->End of Python script error report<--

2022-03-19 12:54:20.915 T:297897    INFO <general>: Python interpreter stopped

CatchUp marche nickel lui...
Pi4 BullEye 64bits

**Comment by BreizhReloaded** [comment]
@FuraX49 Tu peux ouvrir une issue pour ton problème plutôt ? Cela semble différent du problème évoqué par Guibol22. 

Par ailleurs, Catch-Up TV & More sont deux outils très différents, à moins d'utiliser la TV via cet outil. Le replay ne passe pas par PVR IPTV Simple Client, ce qui change un peu le comportement de Kodi.

**Comment by Guibol22** [comment]
> Salut ! Tu as ce problème là uniquement pendant la lecture des flux TV ? Est-ce que tu as essayé la TV via CatchUp TV & More en plus du replay ? Histoire de voir si ton problème vient de la lecture des flux vidéo via PVR IPTV Simple en général, ou uniquement de Orange TV.
