### ISSUE TITLE
Problème à la lecture d'une chaine TV

### ISSUE THREAD

**Issue by patneze** [f-lawe/plugin.video.orange.fr#28]
Bonjour,
je viens de trouver ce plugin très sympa. Merci pour le dev déjà.
Ma config: Windows 11 / client SOSH
Apèrs installation, je vois bien les chaines dans l'onglet TV. Par contre, j'ai une erreur de lecture lorsque je lance une chaine TV. 

Voici le log sur Kodi: 
2022-10-24 23:58:31.340 T:2940     INFO <general>: Orange TV France: Loading channel 47
2022-10-24 23:58:31.522 T:2940    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'stream_info' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "C:\....\addons\plugin.video.orange.fr\resources\addon.py", line 58, in <module>
                                                       plugin.run()
                                                     File "C:\....\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\....\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\....\addons\plugin.video.orange.fr\resources\addon.py", line 24, in channel
                                                       stream = get_provider().get_stream_info(channel_id)
                                                     File "C:\....\addons\plugin.video.orange.fr\resources\lib\providers\provider_wrapper.py", line 24, in get_stream_info
                                                       return self.provider.get_stream_info(channel_id)
                                                     File "C:\....\addons\plugin.video.orange.fr\resources\lib\provider_templates\orange.py", line 45, in get_stream_info
                                                       for system in stream_info.get('protectionData'):
                                                   UnboundLocalError: local variable 'stream_info' referenced before assignment
                                                   -->End of Python script error report<--
                                                   
2022-10-24 23:58:31.553 T:2940     INFO <general>: Python interpreter stopped

Désolé je ne suis pas un pro de Kodi. Un peu d'aide merci.

**Comment by CoderReloaded** [comment]
L'erreur est un problème de récupération des infos de flux des chaînes. Pour la résoudre, il suffit d'ajouter un controle sur la variable stream_infos avant de l'utilisé car elle est potentiellement vide. Ce n'est pas une erreur bloquante en soit dans la mesure où les informations de flux est accessible.

Je note que vous êtes client Sosh, avez-vous activé la TV sur votre abonnement ? 

Le cas échéant, cette url s'affiche-t-elle correctement dans votre navigateur ?
https://mediation-tv.orange.fr/all/live/v3/applications/PC/users/me/channels/192/stream?terminalModel=WEB_PC

**Comment by patneze** [comment]
J'ai désactivé l'option su rmon abo SOSH. Aucun intérêt pour moi.

L'erreur retournée sur l'URL ci-dessus est:
{"code":60,"message":"Resource not found","param":{},"description":"L'URI demandé ou la ressource demandée n'existe pas.","stackTrace":null}

**Comment by CoderReloaded** [comment]
Vous avez la réponse à votre problème. Vous n'avez pas accès aux chaînes orange pour cet addon.
